source 'https://github.com/LiuYimin/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFAuthorKit_Example' do
  pod 'FFAuthorKit', :path => '../'

  target 'FFAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
